on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  "5 4 * * sun"
  
name: 06-event-schedule

jobs:
  run-r-script:
    runs-on: ubuntu-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true

      - name: run-script
        run: Rscript scripts/03-r-script.R        
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
